version: "3"
services:
  jupyter_ds:
    build: ./jupyter
    #restart: unless-stopped
    container_name: jupyter_ds  
    ports:
      - "8888:8888"
    user: ${USERNAME}
    volumes:
      - "./:/home/${USERNAME}/work"
    working_dir: /home/${USERNAME}/work/notebooks        
    command: jupyter notebook --ip 0.0.0.0
    
    